data: [{
        id: 1,
        title: 'Lorem ipsum dolor',
        time: '1 days a go',
        description: 'lorem ipsum dolor amet bla bla bla',
        status: 1,
        image: 'https://lorempixel.com/400/200/nature/6/',
    },
    {
        id: 2,
        title: 'Sit amet, consectetuer',
        time: '2 minutes a go',
        description: 'lorem ipsum dolor amet bla bla bla',
        status: 2,
        image: 'https://lorempixel.com/400/200/nature/5/',
    },
    {
        id: 3,
        title: 'Dipiscing elit. Aenean ',
        time: '3 hour a go',
        description: 'lorem ipsum dolor amet bla bla bla',
        status: 3,
        image: 'https://lorempixel.com/400/200/nature/4/',
    },
    {
        id: 4,
        title: 'Commodo ligula eget dolor.',
        time: '4 months a go',
        description: 'lorem ipsum dolor amet bla bla bla',
        status: 1,
        image: 'https://lorempixel.com/400/200/nature/6/',
    },
    {
        id: 5,
        title: 'Aenean massa. Cum sociis',
        time: '5 weeks a go',
        description: 'lorem ipsum dolor amet bla bla bla',
        status: 1,
        image: 'https://lorempixel.com/400/200/sports/1/',
    },
    {
        id: 6,
        title: 'Natoque penatibus et magnis',
        time: '6 year a go',
        description: 'lorem ipsum dolor amet bla bla bla',
        status: 3,
        image: 'https://lorempixel.com/400/200/nature/8/',
    },
    {
        id: 7,
        title: 'Dis parturient montes, nascetur',
        time: '7 minutes a go',
        description: 'lorem ipsum dolor amet bla bla bla',
        status: 1,
        image: 'https://lorempixel.com/400/200/nature/1/',
    },
    {
        id: 8,
        title: 'Ridiculus mus. Donec quam',
        time: '8 days a go',
        description: 'lorem ipsum dolor amet bla bla bla',
        status: 1,
        image: 'https://lorempixel.com/400/200/nature/3/',
    },
    {
        id: 9,
        title: 'Felis, ultricies nec, pellentesque',
        time: '9 minutes a go',
        description: 'lorem ipsum dolor amet bla bla bla',
        status: 2,
        image: 'https://lorempixel.com/400/200/nature/4/',
    },
],